### ISSUE TITLE
关于漫画柜的域名

### ISSUE THREAD

**Issue by wesleyx2** [hardwarecode/onecomic#10]
目前漫画柜这个站有两个域名
一个是墙外网站 manhuagui.com（除了台湾ip我挂其他地方梯子都进不去包括香港）
一个是国内可以直接访问的 mhgui.com（除了部分和谐资源不显示外资源还是挺多的）
现在问题是可以访问主域名manhuagui的ip太少  而且下载的时候基本都提示无法访问（不知道是不是已经失效了还是ip被封了，这个站封ip很狠基本下几话漫画一个ip就被封一天了）
希望能够支持一下mhgui.com这个域名的下载 这样就可以很方便的下载到大部分漫画了

下面是下载时候的错误信息
2021/07/09 22:18:11 onecomic.worker 19 [INFO] set worker. worker=4
2021/07/09 22:18:11 onecomic.cli 292 [INFO] set proxy. socks5://127.0.0.1:4781
Traceback (most recent call last):
  File "C:\Python\oc\onecomic\crawlerbase.py", line 257, in send_request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python\lib\site-packages\httpx\_client.py", line 785, in request
    return self.send(
  File "C:\Python\lib\site-packages\httpx\_client.py", line 871, in send
    response = self._send_handling_auth(
  File "C:\Python\lib\site-packages\httpx\_client.py", line 907, in _send_handling_auth
    response = self._send_handling_redirects(
  File "C:\Python\lib\site-packages\httpx\_client.py", line 943, in _send_handling_redirects
    response = self._send_single_request(request, timeout)
  File "C:\Python\lib\site-packages\httpx\_client.py", line 977, in _send_single_request
    (status_code, headers, stream, extensions) = transport.handle_request(
  File "C:\Python\lib\site-packages\httpx_socks\_sync_transport.py", line 43, in handle_request
    socket = self._connect_via_proxy(
  File "C:\Python\lib\site-packages\httpx_socks\_sync_transport.py", line 84, in _connect_via_proxy
    sock = ssl_context.wrap_socket(
  File "C:\Python\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Python\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "C:\Python\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
socket.timeout: _ssl.c:1105: The handshake operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Python\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python\oc\onecomic\__main__.py", line 4, in <module>
    main()
  File "C:\Python\oc\onecomic\cli.py", line 395, in main
    comicbook.start_crawler()
  File "C:\Python\oc\onecomic\comicbook.py", line 97, in start_crawler
    self.refresh()
  File "C:\Python\oc\onecomic\comicbook.py", line 100, in refresh
    self.comicbook_item = self.crawler.get_comicbook_item()
  File "C:\Python\oc\onecomic\site\manhuagui.py", line 41, in get_comicbook_item
    soup = self.get_soup(self.source_url)
  File "C:\Python\oc\onecomic\crawlerbase.py", line 275, in get_soup
    html = self.get_html(url, encoding=encoding, **kwargs)
  File "C:\Python\oc\onecomic\crawlerbase.py", line 263, in get_html
    response = self.send_request("GET", url, **kwargs)
  File "C:\Python\oc\onecomic\crawlerbase.py", line 260, in send_request
    raise URLException(msg) from e
onecomic.exceptions.URLException: NETWORK ERROR. can not open url: https://www.manhuagui.com/comic/1115/

**Comment by BeiAduo** [comment]
你所遇到到的问题 ，几个月前我就弄了，不推荐采集着这个站点用台湾代理，能完整抓取到数据后，你会发现api返回数据慢，下载图片 就更慢了！最后我已放弃了！
