### ISSUE TITLE
cocomanhua抓取失效了

### ISSUE THREAD

**Issue by wesleyx2** [hardwarecode/onecomic#11]
错误带码如下：

2021/07/31 21:18:32 onecomic.config 86 [INFO] loading config. config=config.ini
2021/07/31 21:18:32 onecomic.worker 19 [INFO] set worker. worker=4
Traceback (most recent call last):
  File "C:\Python\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python\oc\onecomic\__main__.py", line 4, in <module>
    main()
  File "C:\Python\oc\onecomic\cli.py", line 395, in main
    comicbook.start_crawler()
  File "C:\Python\oc\onecomic\comicbook.py", line 97, in start_crawler
    self.refresh()
  File "C:\Python\oc\onecomic\comicbook.py", line 100, in refresh
    self.comicbook_item = self.crawler.get_comicbook_item()
  File "C:\Python\oc\onecomic\site\cocomanhua.py", line 39, in get_comicbook_item
    status = soup.find('span', text='状态').parent.a.text
AttributeError: 'NoneType' object has no attribute 'parent'

**Comment by mustvvvics** [comment]
同coco：
2021/10/01 10:32:12 onecomic.worker 19 [INFO] set worker. worker=4                                                      
Traceback (most recent call last):                                                                                        
File "C:\Python39\lib\runpy.py", line 197, in _run_module_as_main                                                         
return _run_code(code, main_globals, None,                                                                            
File "C:\Python39\lib\runpy.py", line 87, in _run_code                                                                    
exec(code, run_globals)                                                                                               
File "C:\Python39\lib\site-packages\onecomic\__main__.py", line 4, in <module>                                            
main()                                                                                                                
File "C:\Python39\lib\site-packages\onecomic\cli.py", line 423, in main                                                   
comicbook = ComicBook(site=site, comicid=comicid)                                                                    
 File "C:\Python39\lib\site-packages\onecomic\comicbook.py", line 68, in __init__                                         
 self.crawler = crawler_cls(comicid)                                                                                  
 File "C:\Python39\lib\site-packages\onecomic\crawlerbase.py", line 234, in __init__                                       self.chekc_node_modules()                                                                                             
File "C:\Python39\lib\site-packages\onecomic\crawlerbase.py", line 452, in chekc_node_modules                             
raise RuntimeError(                                                                                                 
RuntimeError: pleaese set node_modules directory and install crypto-js first. npm install crypto-js

**Comment by hardwarecode** [comment]
该站点上了Cloudflare，暂时没方案处理
