### ISSUE TITLE
不兼容Python 3.10

### ISSUE THREAD

**Issue by fuchanghao** [hardwarecode/onecomic#15]
在3.10下无法运行，会报错，回退到3.9.9才正常。

运行代码示例

python -m onecomic -s bilibili -id mc30332 --all --cookies-path="bilibili.json"

报错信息：

```
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python310\site-packages\onecomic\__main__.py", line 3, in <module>
    from .cli import main
  File "C:\Users\Administrator\AppData\Roaming\Python\Python310\site-packages\onecomic\cli.py", line 6, in <module>
    from .comicbook import ComicBook
  File "C:\Users\Administrator\AppData\Roaming\Python\Python310\site-packages\onecomic\comicbook.py", line 19, in <module>
    from .crawlerbase import CrawlerBase
  File "C:\Users\Administrator\AppData\Roaming\Python\Python310\site-packages\onecomic\crawlerbase.py", line 12, in <module>
    from .session import CrawlerSession
  File "C:\Users\Administrator\AppData\Roaming\Python\Python310\site-packages\onecomic\session.py", line 4, in <module>
    import httpx
  File "C:\Users\Administrator\AppData\Roaming\Python\Python310\site-packages\httpx\__init__.py", line 2, in <module>
    from ._api import delete, get, head, options, patch, post, put, request, stream
  File "C:\Users\Administrator\AppData\Roaming\Python\Python310\site-packages\httpx\_api.py", line 4, in <module>
    from ._client import Client
  File "C:\Users\Administrator\AppData\Roaming\Python\Python310\site-packages\httpx\_client.py", line 30, in <module>
    from ._transports.default import AsyncHTTPTransport, HTTPTransport
  File "C:\Users\Administrator\AppData\Roaming\Python\Python310\site-packages\httpx\_transports\default.py", line 30, in <module>
    import httpcore
  File "C:\Users\Administrator\AppData\Roaming\Python\Python310\site-packages\httpcore\__init__.py", line 1, in <module>
    from ._api import request, stream
  File "C:\Users\Administrator\AppData\Roaming\Python\Python310\site-packages\httpcore\_api.py", line 5, in <module>
    from ._sync.connection_pool import ConnectionPool
  File "C:\Users\Administrator\AppData\Roaming\Python\Python310\site-packages\httpcore\_sync\__init__.py", line 8, in <module>
    from .http2 import HTTP2Connection
  File "C:\Users\Administrator\AppData\Roaming\Python\Python310\site-packages\httpcore\_sync\http2.py", line 7, in <module>
    import h2.connection
  File "C:\Users\Administrator\AppData\Roaming\Python\Python310\site-packages\h2\connection.py", line 13, in <module>
    from hyperframe.frame import (
  File "C:\Users\Administrator\AppData\Roaming\Python\Python310\site-packages\hyperframe\frame.py", line 17, in <module>
    from .flags import Flag, Flags
  File "C:\Users\Administrator\AppData\Roaming\Python\Python310\site-packages\hyperframe\flags.py", line 14, in <module>
    class Flags(collections.MutableSet):
AttributeError: module 'collections' has no attribute 'Mut
```ableSet'

**Comment by hardwarecode** [comment]
上游依赖的包的问题，本项目不处理

**Comment by lossme** [comment]
可以尝试升级一下依赖包解决
python3 -m pip install -U h2
