### ISSUE TITLE
报错 b漫下载出错了

### ISSUE THREAD

**Issue by wesleyx2** [hardwarecode/onecomic#17]
错误信息
2021/12/14 13:18:30 onecomic.config 97 [INFO] loading config. config=config.ini
2021/12/14 13:18:30 onecomic.worker 19 [INFO] set worker. worker=4
2021/12/14 13:18:30 onecomic.cli 296 [INFO] set proxy. socks5://127.0.0.1:4781
2021/12/14 13:18:30 onecomic.cli 308 [INFO] load cookies success. bilibili.json
2021/12/14 13:18:30 onecomic.cli 290 [INFO] 哔哩哔哩漫画 comicid=28502 【公主大人，接下来是“拷问”时间】 更新至: 126 拷问123 数据来源: https://manga.bilibili.com/m/detail/mc28502
2021/12/14 13:18:31 onecomic.cli 172 [ERROR] download comicbook error. site=bilibili comicid=28502 chapter_number=126
Traceback (most recent call last):
  File "C:\Python\oc\onecomic\cli.py", line 148, in download_main
    chapter = comicbook.Chapter(chapter_number, ext_name=ext_name)
  File "C:\Python\oc\onecomic\comicbook.py", line 168, in Chapter
    chapter_item = self.crawler.get_chapter_item(chapter_item)
  File "C:\Python\oc\onecomic\crawlerbase.py", line 307, in get_chapter_item
    image_urls = self.get_chapter_image_urls(citem)
  File "C:\Python\oc\onecomic\site\bilibili.py", line 132, in get_chapter_image_urls
    chapter_api_data = self.get_chapter_api_data(cid=citem.cid)
  File "C:\Python\oc\onecomic\site\bilibili.py", line 84, in get_chapter_api_data
    raise ChapterNotFound(f"Please read on bilibili Manga APP. {source_url}")
onecomic.exceptions.ChapterNotFound: Please read on bilibili Manga APP. https://manga.bilibili.com/mc28502/666738

**Comment by hardwarecode** [comment]
已修复
